package model;
// Generated 18-may-2020 19:16:17 by Hibernate Tools 4.3.1



/**
 * Frequest generated by hbm2java
 */
public class Frequest  implements java.io.Serializable {


     private Integer id;
     private User userByDestUser;
     private User userByOrigUser;

    public Frequest() {
    }

    public Frequest(User userByDestUser, User userByOrigUser) {
       this.userByDestUser = userByDestUser;
       this.userByOrigUser = userByOrigUser;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUserByDestUser() {
        return this.userByDestUser;
    }
    
    public void setUserByDestUser(User userByDestUser) {
        this.userByDestUser = userByDestUser;
    }
    public User getUserByOrigUser() {
        return this.userByOrigUser;
    }
    
    public void setUserByOrigUser(User userByOrigUser) {
        this.userByOrigUser = userByOrigUser;
    }
}


