package model;
// Generated 18-may-2020 19:16:17 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable, Comparable {


     private Integer id;
     private Topic topic;
     private User user;
     private String content;
     private Date datetime;

    public Message() {
    }

    public Message(Topic topic, User user, String content, Date datetime) {
       this.topic = topic;
       this.user = user;
       this.content = content;
       this.datetime = datetime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Topic getTopic() {
        return this.topic;
    }
    
    public void setTopic(Topic topic) {
        this.topic = topic;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    @Override
    public int compareTo(Object m) {
        return this.getDatetime().compareTo(((Message)m).getDatetime());
    }
}


