package model;
// Generated 18-may-2020 19:16:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Topic generated by hbm2java
 */
public class Topic  implements java.io.Serializable, Comparable {


     private int id;
     private String title;
     private Set trequests = new HashSet(0);
     private Set messages = new HashSet(0);
     private Set users = new HashSet(0);

    public Topic() {
    }

    public Topic(String title) {
        this.title = title;
    }
    
    public Topic(int id, String title, Set trequests, Set messages, Set users) {
       this.id = id;
       this.title = title;
       this.trequests = trequests;
       this.messages = messages;
       this.users = users;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Set getTrequests() {
        return this.trequests;
    }
    
    public void setTrequests(Set trequests) {
        this.trequests = trequests;
    }
    public Set getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set messages) {
        this.messages = messages;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }

    @Override
    public int compareTo(Object t) {
        return this.getTitle().compareTo(((Topic)t).getTitle());
    }
}


