package model;
// Generated 18-may-2020 19:16:17 by Hibernate Tools 4.3.1



/**
 * Trequest generated by hbm2java
 */
public class Trequest  implements java.io.Serializable {


     private Integer id;
     private Topic topic;
     private User user;

    public Trequest() {
    }

    public Trequest(Topic topic, User user) {
       this.topic = topic;
       this.user = user;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Topic getTopic() {
        return this.topic;
    }
    
    public void setTopic(Topic topic) {
        this.topic = topic;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
}


