package model;
// Generated 18-may-2020 19:16:17 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable, Comparable {


     private Integer id;
     private String username;
     private String password;
     private String name;
     private String lastname;
     private Date birthdate;
     private String mail;
     private String photourl;
     private Set trequests = new HashSet(0);
     private Set frequestsForDestUser = new HashSet(0);
     private Set frequestsForOrigUser = new HashSet(0);
     private Set messages = new HashSet(0);
     private Set friends = new HashSet(0);
     private Set topics = new HashSet(0);

    public User() {
    }

    public User(String username, String password, String name, 
            String lastname, Date birthdate, String mail, String photourl) {
        this.username = username;
        this.password = password;
        this.name = name;
        this.lastname = lastname;
        this.birthdate = birthdate;
        this.mail = mail;
        this.photourl = photourl;
    }
    public User(String username, String password, String name, String lastname, 
            Date birthdate, String mail, String photourl, Set trequests, 
            Set frequestsForDestUser, Set frequestsForOrigUser, Set messages, 
            Set friends, Set topics) {
       this.username = username;
       this.password = password;
       this.name = name;
       this.lastname = lastname;
       this.birthdate = birthdate;
       this.mail = mail;
       this.photourl = photourl;
       this.trequests = trequests;
       this.frequestsForDestUser = frequestsForDestUser;
       this.frequestsForOrigUser = frequestsForOrigUser;
       this.messages = messages;
       this.friends = friends;
       this.topics = topics;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }

    public String getPhotourl() {
        return photourl;
    }

    public void setPhotourl(String photourl) {
        this.photourl = photourl;
    }

    public Set getTrequests() {
        return this.trequests;
    }
    
    public void setTrequests(Set trequests) {
        this.trequests = trequests;
    }
    public Set getFrequestsForDestUser() {
        return this.frequestsForDestUser;
    }
    
    public void setFrequestsForDestUser(Set frequestsForDestUser) {
        this.frequestsForDestUser = frequestsForDestUser;
    }
    public Set getFrequestsForOrigUser() {
        return this.frequestsForOrigUser;
    }
    
    public void setFrequestsForOrigUser(Set frequestsForOrigUser) {
        this.frequestsForOrigUser = frequestsForOrigUser;
    }
    public Set getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set messages) {
        this.messages = messages;
    }

    public Set getFriends() {
        return friends;
    }

    public void setFriends(Set friends) {
        this.friends = friends;
    }

    public Set getTopics() {
        return topics;
    }

    public void setTopics(Set topics) {
        this.topics = topics;
    }

    @Override
    public int compareTo(Object u) {
        return this.getUsername().compareTo(((User)u).getUsername());
    }
}


