/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import model.User;

/**
 *
 * @author Ayoze Gil
 */
public final class ListFriendPanel extends javax.swing.JPanel {

    private User user;
    
    /**
     * Creates new form FriendPanel
     */
    public ListFriendPanel() {
        initComponents(); 
    }
    
    public ListFriendPanel(User user) {
        initComponents();
        this.user = user;
        ImageIcon imgicon = new ImageIcon("./src/resources/"+user.getId()+".png");
        imgicon = new ImageIcon(imgicon.getImage().getScaledInstance(60, 75, Image.SCALE_SMOOTH));
        JLabel Img = new JLabel(imgicon);
        Img.setSize(60, 75);
        this.getLblPhoto().add(Img);
        this.getLblUsername().setText(this.user.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsername = new javax.swing.JLabel();
        btnTopic = new javax.swing.JButton();
        btnUnfriend = new javax.swing.JButton();
        lblPhoto = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(200, 100));
        setMinimumSize(new java.awt.Dimension(200, 100));

        lblUsername.setForeground(new java.awt.Color(0, 0, 255));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("Usuario Amigo");
        lblUsername.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnTopic.setForeground(new java.awt.Color(255, 102, 0));
        btnTopic.setText("Invitar al Tema");
        btnTopic.setActionCommand("Auto_Topic_Request");
        btnTopic.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnUnfriend.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUnfriend.setForeground(new java.awt.Color(255, 0, 51));
        btnUnfriend.setText("x");
        btnUnfriend.setActionCommand("Delete_Friend");
        btnUnfriend.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUnfriend.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnUnfriend.setMaximumSize(new java.awt.Dimension(20, 20));
        btnUnfriend.setMinimumSize(new java.awt.Dimension(20, 20));
        btnUnfriend.setPreferredSize(new java.awt.Dimension(25, 25));

        lblPhoto.setIcon(new javax.swing.ImageIcon("C:\\Users\\AN\\Desktop\\AyozeGS_ORM_final\\src\\resources\\default_profile 60x75.jpg")); // NOI18N
        lblPhoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblPhoto.setMaximumSize(new java.awt.Dimension(60, 75));
        lblPhoto.setMinimumSize(new java.awt.Dimension(60, 75));
        lblPhoto.setPreferredSize(new java.awt.Dimension(60, 75));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(btnUnfriend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTopic, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(btnTopic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUnfriend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTopic;
    private javax.swing.JButton btnUnfriend;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables

    public User getUser() {
        return user;
    }

    public JButton getBtnTopic() {
        return btnTopic;
    }

    public JButton getBtnUnfriend() {
        return btnUnfriend;
    }

    public JLabel getLblUsername() {
        return lblUsername;
    }

    public JLabel getLblPhoto() {
        return lblPhoto;
    }
}
