/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import model.Topic;

/**
 *
 * @author Ayoze Gil Sosa
 */
public class ListMessagePanel extends javax.swing.JPanel {

    Topic topic;
    /**
     * Creates new form CenterTopicPanel
     */
    public ListMessagePanel() {
        initComponents();
    }
    
    public ListMessagePanel(Topic topic) {
        initComponents();
        this.topic = topic;
        initProcess();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newMessagePanel = new javax.swing.JPanel();
        txtNewMessage = new javax.swing.JTextField();
        btnSendMessage = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        scPanelMessages = new javax.swing.JScrollPane();
        messagesPanel = new javax.swing.JPanel();
        scPanelUsers = new javax.swing.JScrollPane();
        usersPanel = new javax.swing.JPanel();

        setOpaque(false);

        newMessagePanel.setBackground(new java.awt.Color(255, 204, 153));
        newMessagePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        newMessagePanel.setFocusCycleRoot(true);
        newMessagePanel.setMaximumSize(new java.awt.Dimension(32767, 47));
        newMessagePanel.setMinimumSize(new java.awt.Dimension(100, 47));

        btnSendMessage.setText("Enviar");
        btnSendMessage.setActionCommand("Send_Message");
        btnSendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendMessageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newMessagePanelLayout = new javax.swing.GroupLayout(newMessagePanel);
        newMessagePanel.setLayout(newMessagePanelLayout);
        newMessagePanelLayout.setHorizontalGroup(
            newMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newMessagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNewMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSendMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        newMessagePanelLayout.setVerticalGroup(
            newMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newMessagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNewMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTitle.setBackground(new java.awt.Color(255, 204, 153));
        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 51, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Tema");
        lblTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblTitle.setOpaque(true);

        scPanelMessages.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scPanelMessages.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        messagesPanel.setBackground(new java.awt.Color(255, 204, 153));
        messagesPanel.setLayout(new javax.swing.BoxLayout(messagesPanel, javax.swing.BoxLayout.Y_AXIS));
        scPanelMessages.setViewportView(messagesPanel);

        scPanelUsers.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scPanelUsers.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scPanelUsers.setMaximumSize(new java.awt.Dimension(100, 32767));
        scPanelUsers.setMinimumSize(new java.awt.Dimension(100, 23));

        usersPanel.setBackground(new java.awt.Color(255, 204, 153));
        usersPanel.setMaximumSize(new java.awt.Dimension(100, 32767));
        usersPanel.setPreferredSize(new java.awt.Dimension(100, 397));
        usersPanel.setLayout(new javax.swing.BoxLayout(usersPanel, javax.swing.BoxLayout.Y_AXIS));
        scPanelUsers.setViewportView(usersPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scPanelUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scPanelMessages, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(newMessagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scPanelMessages)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newMessagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scPanelUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSendMessageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendMessage;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel messagesPanel;
    private javax.swing.JPanel newMessagePanel;
    private javax.swing.JScrollPane scPanelMessages;
    private javax.swing.JScrollPane scPanelUsers;
    private javax.swing.JTextField txtNewMessage;
    private javax.swing.JPanel usersPanel;
    // End of variables declaration//GEN-END:variables

    private void initProcess() {
        this.getScPanelMessages().getViewport().setOpaque(false);
        this.getScPanelUsers().getViewport().setOpaque(false);
    }
    
    public Topic getTopic() {
        return topic;
    }

    public JButton getBtnSendMessage() {
        return btnSendMessage;
    }

    public JLabel getLblTitle() {
        return lblTitle;
    }

    public JPanel getMessagesPanel() {
        return messagesPanel;
    }

    public JScrollPane getScPanelMessages() {
        return scPanelMessages;
    }

    public JScrollPane getScPanelUsers() {
        return scPanelUsers;
    }

    public JTextField getTxtNewMessage() {
        return txtNewMessage;
    }

    public JPanel getUsersPanel() {
        return usersPanel;
    }

    public JPanel getNewMessagePanel() {
        return newMessagePanel;
    }
}
