/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import model.Topic;

/**
 *
 * @author Ayoze Gil
 */
public final class ListTopicPanel extends javax.swing.JPanel {

    Topic topic;
    
    /**
     * Creates new form TopicPanel
     */
    public ListTopicPanel() {
        initComponents();
    }

    public ListTopicPanel(Topic topic) {
        initComponents();
        this.topic = topic;
        this.getBtnTitle().setText(this.topic.getTitle());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddFriend = new javax.swing.JButton();
        btnTitle = new javax.swing.JButton();
        btnLeaveTopic = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(270, 30));
        setMinimumSize(new java.awt.Dimension(270, 30));
        setName(""); // NOI18N
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(270, 30));

        btnAddFriend.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddFriend.setForeground(new java.awt.Color(0, 153, 0));
        btnAddFriend.setText("+");
        btnAddFriend.setActionCommand("Invite_Friend");
        btnAddFriend.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnAddFriend.setMaximumSize(new java.awt.Dimension(15, 23));
        btnAddFriend.setMinimumSize(new java.awt.Dimension(15, 23));
        btnAddFriend.setPreferredSize(new java.awt.Dimension(15, 23));

        btnTitle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTitle.setText("Titulo");
        btnTitle.setActionCommand("Open_Topic");
        btnTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTitle.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnTitle.setMaximumSize(new java.awt.Dimension(203, 23));
        btnTitle.setMinimumSize(new java.awt.Dimension(203, 23));
        btnTitle.setPreferredSize(new java.awt.Dimension(203, 23));

        btnLeaveTopic.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLeaveTopic.setForeground(new java.awt.Color(204, 0, 0));
        btnLeaveTopic.setText("x");
        btnLeaveTopic.setActionCommand("Delete_Topic");
        btnLeaveTopic.setMargin(new java.awt.Insets(2, 2, 2, 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLeaveTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddFriend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLeaveTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFriend;
    private javax.swing.JButton btnLeaveTopic;
    private javax.swing.JButton btnTitle;
    // End of variables declaration//GEN-END:variables

    public Topic getTopic() {
        return topic;
    }

    public JButton getBtnAddFriend() {
        return btnAddFriend;
    }

    public JButton getBtnTitle() {
        return btnTitle;
    }

    public JButton getBtnLeaveTopic() {
        return btnLeaveTopic;
    }
}
