/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Ayoze Gil Sosa
 */
public class SessionPanel extends javax.swing.JPanel {

    /**
     * Creates new form panel
     */
    public SessionPanel() {
        initComponents();
        initProcess();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuOption = new javax.swing.JDialog();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        northPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        btnExitSession = new javax.swing.JButton();
        btnConfig = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();
        eastPanel = new javax.swing.JPanel();
        scPanelTopics = new javax.swing.JScrollPane();
        topicsPanel = new javax.swing.JPanel();
        westPanel = new javax.swing.JPanel();
        scPanelFriends = new javax.swing.JScrollPane();
        friendsPanel = new javax.swing.JPanel();
        southPanel = new javax.swing.JPanel();
        lblHelpMessage = new javax.swing.JLabel();
        btnCreateTopic = new javax.swing.JButton();
        btnFriendRequest = new javax.swing.JButton();

        menuOption.setTitle("Opciones de Cuenta");
        menuOption.setMinimumSize(new java.awt.Dimension(300, 150));
        menuOption.setSize(new java.awt.Dimension(300, 150));
        menuOption.getContentPane().setLayout(new java.awt.GridLayout(3, 0));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 102, 0));
        btnUpdate.setText("Modificar Datos");
        btnUpdate.setActionCommand("Update_Account");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        menuOption.getContentPane().add(btnUpdate);

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 102, 0));
        btnDelete.setText("Borrar Cuenta");
        btnDelete.setActionCommand("Delete_Account");
        menuOption.getContentPane().add(btnDelete);

        btnAdmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(255, 102, 0));
        btnAdmin.setText("Panel Administrador (No Disp)");
        btnAdmin.setActionCommand("Open_Admin");
        menuOption.getContentPane().add(btnAdmin);

        setMinimumSize(new java.awt.Dimension(958, 488));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(958, 488));
        setLayout(new java.awt.BorderLayout());

        northPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        northPanel.setMaximumSize(new java.awt.Dimension(32767, 130));
        northPanel.setMinimumSize(new java.awt.Dimension(958, 130));
        northPanel.setOpaque(false);

        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setIcon(new javax.swing.ImageIcon("C:\\Users\\AN\\Desktop\\AyozeGS_ORM_final\\src\\resources\\background_nombre.png")); // NOI18N
        lblTitle.setMaximumSize(new java.awt.Dimension(651, 130));
        lblTitle.setMinimumSize(new java.awt.Dimension(651, 130));
        lblTitle.setPreferredSize(new java.awt.Dimension(651, 130));

        lblUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(0, 102, 255));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("Usuario");

        lblPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhoto.setIcon(new javax.swing.ImageIcon("C:\\Users\\AN\\Desktop\\AyozeGS_ORM_Hibernetwork\\src\\resources\\default_profile 60x75.jpg")); // NOI18N
        lblPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        lblPhoto.setMaximumSize(new java.awt.Dimension(60, 75));
        lblPhoto.setMinimumSize(new java.awt.Dimension(60, 75));
        lblPhoto.setPreferredSize(new java.awt.Dimension(60, 75));

        btnExitSession.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExitSession.setIcon(new javax.swing.ImageIcon("C:\\Users\\AN\\Desktop\\AyozeGS_ORM_Hibernetwork\\src\\resources\\logout.png")); // NOI18N
        btnExitSession.setText("Salir");
        btnExitSession.setActionCommand("Exit_Session");

        btnConfig.setIcon(new javax.swing.ImageIcon("C:\\Users\\AN\\Desktop\\AyozeGS_ORM_Hibernetwork\\src\\resources\\config.png")); // NOI18N
        btnConfig.setActionCommand("Config_Options");
        btnConfig.setMargin(new java.awt.Insets(0, 0, 0, 0));

        btnRefresh.setIcon(new javax.swing.ImageIcon("C:\\Users\\AN\\Desktop\\AyozeGS_ORM_Hibernetwork\\src\\resources\\refresh.png")); // NOI18N
        btnRefresh.setActionCommand("Refresh");
        btnRefresh.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnRefresh.setMaximumSize(new java.awt.Dimension(125, 25));
        btnRefresh.setMinimumSize(new java.awt.Dimension(125, 25));
        btnRefresh.setPreferredSize(new java.awt.Dimension(125, 25));

        javax.swing.GroupLayout northPanelLayout = new javax.swing.GroupLayout(northPanel);
        northPanel.setLayout(northPanelLayout);
        northPanelLayout.setHorizontalGroup(
            northPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(northPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExitSession, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(northPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(northPanelLayout.createSequentialGroup()
                        .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(northPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        northPanelLayout.setVerticalGroup(
            northPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(northPanelLayout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(northPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(northPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(northPanelLayout.createSequentialGroup()
                        .addComponent(btnExitSession, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(northPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(northPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(northPanelLayout.createSequentialGroup()
                                .addComponent(btnConfig)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        add(northPanel, java.awt.BorderLayout.PAGE_START);

        centerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        centerPanel.setOpaque(false);

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );

        add(centerPanel, java.awt.BorderLayout.CENTER);

        eastPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        eastPanel.setMaximumSize(new java.awt.Dimension(290, 32767));
        eastPanel.setMinimumSize(new java.awt.Dimension(280, 0));
        eastPanel.setOpaque(false);
        eastPanel.setPreferredSize(new java.awt.Dimension(290, 0));
        eastPanel.setRequestFocusEnabled(false);

        scPanelTopics.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scPanelTopics.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scPanelTopics.setMaximumSize(new java.awt.Dimension(270, 32767));
        scPanelTopics.setMinimumSize(new java.awt.Dimension(270, 120));
        scPanelTopics.setOpaque(false);
        scPanelTopics.setPreferredSize(new java.awt.Dimension(270, 120));

        topicsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        topicsPanel.setMaximumSize(new java.awt.Dimension(270, 1000));
        topicsPanel.setMinimumSize(new java.awt.Dimension(270, 150));
        topicsPanel.setOpaque(false);
        topicsPanel.setPreferredSize(new java.awt.Dimension(270, 0));
        topicsPanel.setLayout(new javax.swing.BoxLayout(topicsPanel, javax.swing.BoxLayout.Y_AXIS));
        scPanelTopics.setViewportView(topicsPanel);

        javax.swing.GroupLayout eastPanelLayout = new javax.swing.GroupLayout(eastPanel);
        eastPanel.setLayout(eastPanelLayout);
        eastPanelLayout.setHorizontalGroup(
            eastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scPanelTopics, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
        );
        eastPanelLayout.setVerticalGroup(
            eastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scPanelTopics, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
        );

        add(eastPanel, java.awt.BorderLayout.EAST);

        westPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        westPanel.setAutoscrolls(true);
        westPanel.setMaximumSize(new java.awt.Dimension(225, 32767));
        westPanel.setMinimumSize(new java.awt.Dimension(225, 0));
        westPanel.setOpaque(false);
        westPanel.setPreferredSize(new java.awt.Dimension(225, 0));

        scPanelFriends.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scPanelFriends.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scPanelFriends.setMaximumSize(null);
        scPanelFriends.setMinimumSize(null);
        scPanelFriends.setOpaque(false);

        friendsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        friendsPanel.setOpaque(false);
        friendsPanel.setLayout(new javax.swing.BoxLayout(friendsPanel, javax.swing.BoxLayout.Y_AXIS));
        scPanelFriends.setViewportView(friendsPanel);

        javax.swing.GroupLayout westPanelLayout = new javax.swing.GroupLayout(westPanel);
        westPanel.setLayout(westPanelLayout);
        westPanelLayout.setHorizontalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scPanelFriends, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
        );
        westPanelLayout.setVerticalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scPanelFriends, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
        );

        add(westPanel, java.awt.BorderLayout.WEST);

        southPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        southPanel.setOpaque(false);

        lblHelpMessage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHelpMessage.setForeground(new java.awt.Color(0, 0, 255));
        lblHelpMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHelpMessage.setAlignmentX(0.5F);

        btnCreateTopic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCreateTopic.setForeground(new java.awt.Color(255, 102, 0));
        btnCreateTopic.setText("Crear Tema");
        btnCreateTopic.setActionCommand("Create_Topic");
        btnCreateTopic.setMaximumSize(new java.awt.Dimension(125, 25));
        btnCreateTopic.setMinimumSize(new java.awt.Dimension(125, 25));
        btnCreateTopic.setPreferredSize(new java.awt.Dimension(125, 25));

        btnFriendRequest.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFriendRequest.setForeground(new java.awt.Color(255, 102, 0));
        btnFriendRequest.setText("Solicitud Amistad");
        btnFriendRequest.setActionCommand("Friend_Request");
        btnFriendRequest.setMaximumSize(new java.awt.Dimension(125, 25));
        btnFriendRequest.setMinimumSize(new java.awt.Dimension(125, 25));
        btnFriendRequest.setPreferredSize(new java.awt.Dimension(125, 25));

        javax.swing.GroupLayout southPanelLayout = new javax.swing.GroupLayout(southPanel);
        southPanel.setLayout(southPanelLayout);
        southPanelLayout.setHorizontalGroup(
            southPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(southPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFriendRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHelpMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        southPanelLayout.setVerticalGroup(
            southPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(southPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(southPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(southPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnCreateTopic, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                        .addComponent(lblHelpMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnFriendRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        add(southPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnCreateTopic;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExitSession;
    private javax.swing.JButton btnFriendRequest;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel eastPanel;
    private javax.swing.JPanel friendsPanel;
    private javax.swing.JLabel lblHelpMessage;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JDialog menuOption;
    private javax.swing.JPanel northPanel;
    private javax.swing.JScrollPane scPanelFriends;
    private javax.swing.JScrollPane scPanelTopics;
    private javax.swing.JPanel southPanel;
    private javax.swing.JPanel topicsPanel;
    private javax.swing.JPanel westPanel;
    // End of variables declaration//GEN-END:variables

    
    private void initProcess(){
        this.getScPanelFriends().getViewport().setOpaque(false);
        this.getScPanelTopics().getViewport().setOpaque(false);
        this.getCenterPanel().setSize(0,0);
        this.getEastPanel().setSize(1700,800);
        //Administrador inhabilitado por defecto hasta implementación
        this.getBtnAdmin().setEnabled(false);
        this.getMenuOption().setLocationRelativeTo(this);
    }
    
    public JButton getBtnFriendRequest() {
        return btnFriendRequest;
    }
    
    public JLabel getLblHelpMessage() {
        return lblHelpMessage;
    }

    public JButton getBtnCreateTopic() {
        return btnCreateTopic;
    }

    public JLabel getLblPhoto() {
        return lblPhoto;
    }
   
    public JLabel getLblUsername() {
        return lblUsername;
    }

    public JScrollPane getScPanelFriends() {
        return scPanelFriends;
    }

    public JPanel getFriendsPanel() {
        return friendsPanel;
    }

    public JScrollPane getScPanelTopics() {
        return scPanelTopics;
    }

    public JPanel getTopicsPanel() {
        return topicsPanel;
    }

    public JButton getBtnExitSession() {
        return btnExitSession;
    }

    public JButton getBtnRefresh() {
        return btnRefresh;
    }

    public JPanel getCenterPanel() {
        return centerPanel;
    }

    public JPanel getEastPanel() {
        return eastPanel;
    }

    public JPanel getNorthPanel() {
        return northPanel;
    }

    public JPanel getWestPanel() {
        return westPanel;
    }

    public JPanel getSouthPanel() {
        return southPanel;
    }

    public JButton getBtnAdmin() {
        return btnAdmin;
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }

    public JButton getBtnUpdate() {
        return btnUpdate;
    }

    public JButton getBtnConfig() {
        return btnConfig;
    }

    public JDialog getMenuOption() {
        return menuOption;
    }

    public JLabel getLblTitle() {
        return lblTitle;
    }

    public void setBtnAdmin(JButton btnAdmin) {
        this.btnAdmin = btnAdmin;
    }

    public void setBtnConfig(JButton btnConfig) {
        this.btnConfig = btnConfig;
    }

    public void setBtnCreateTopic(JButton btnCreateTopic) {
        this.btnCreateTopic = btnCreateTopic;
    }

    public void setBtnDelete(JButton btnDelete) {
        this.btnDelete = btnDelete;
    }

    public void setBtnExitSession(JButton btnExitSession) {
        this.btnExitSession = btnExitSession;
    }

    public void setBtnFriendRequest(JButton btnFriendRequest) {
        this.btnFriendRequest = btnFriendRequest;
    }

    public void setBtnRefresh(JButton btnRefresh) {
        this.btnRefresh = btnRefresh;
    }

    public void setBtnUpdate(JButton btnUpdate) {
        this.btnUpdate = btnUpdate;
    }

    public void setCenterPanel(JPanel centerPanel) {
        this.centerPanel = centerPanel;
    }

    public void setEastPanel(JPanel eastPanel) {
        this.eastPanel = eastPanel;
    }

    public void setFriendsPanel(JPanel friendsPanel) {
        this.friendsPanel = friendsPanel;
    }

    public void setLblHelpMessage(JLabel lblHelpMessage) {
        this.lblHelpMessage = lblHelpMessage;
    }
    public void setLblPhoto(JLabel lblPhoto) {
        this.lblPhoto = lblPhoto;
    }

    public void setLblTitle(JLabel lblTitle) {
        this.lblTitle = lblTitle;
    }

    public void setLblUsername(JLabel lblUsername) {
        this.lblUsername = lblUsername;
    }

    public void setMenuOption(JDialog menuOption) {
        this.menuOption = menuOption;
    }

    public void setNorthPanel(JPanel northPanel) {
        this.northPanel = northPanel;
    }

    public void setScPanelFriends(JScrollPane scPanelFriends) {
        this.scPanelFriends = scPanelFriends;
    }

    public void setScPanelTopics(JScrollPane scPanelTopics) {
        this.scPanelTopics = scPanelTopics;
    }

    public void setSouthPanel(JPanel southPanel) {
        this.southPanel = southPanel;
    }

    public void setTopicsPanel(JPanel topicsPanel) {
        this.topicsPanel = topicsPanel;
    }

    public void setWestPanel(JPanel westPanel) {
        this.westPanel = westPanel;
    }
    
    
}
